#!/bin/bash

application_path=$(pwd)

home_path=($HOME)

echo "application path - $application_path"
echo "home path - $home_path"
sudo apt install cmake
sudo apt-get install curl zip unzip tar

mkdir Dependency
cd  Dependency

# Dependency installation
echo "Started downloading additional files"
git clone https://github.com/Microsoft/vcpkg
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg install nlohmann-json
sudo apt-get install libconfig-dev
echo "Finished downloading additional files"

# Modifying CMakeLists.txt
cd $application_path
sed -i "s|/usr/local|$application_path/Dependency|g" "$application_path/ServerSide/IncludeMake/CMakeLists.txt" 
sed -i "s|/usr/local|$application_path/Dependency|g" "$application_path/ServerSide/ListeningDaemon/CMakeLists.txt" 
sed -i "s|/usr/local|$application_path/Dependency|g" "$application_path/Client/CMakeLists.txt"
sed -i "s|/usr/local|$application_path/Dependency|g" "$application_path/GUI/CMakeLists.txt"

# Moving dependencies
echo "Starting make files"
cd $application_path
sudo mv config.cfg /usr/local/bin
sudo mv ./ServerSide/ListeningDaemon/listening_daemon.service /etc/systemd/system
mkdir ./ServerSide/IncludeMake/build
cd ./ServerSide/IncludeMake/build
cmake ..
sudo make install 
cd $application_path
mkdir ./ServerSide/ListeningDaemon/build
cd ./ServerSide/ListeningDaemon/build
cmake ..
make
cd $application_path
mkdir ./Client/build
cd ./Client/build
cmake ..
make

# Moving daemon.exe
echo "Starting daemon"
cd $application_path

cd ./ServerSide/ListeningDaemon/build
sudo mv ListeningDaemon /usr/local/bin
sudo useradd -m -G adm,sudo -s /bin/bash SEC_OPERATOR
sudo systemctl start listening_daemon.service

sudo touch /home/SEC_OPERATOR/ban_user.txt
sudo touch /home/SEC_OPERATOR/__info.txt
sudo chown SEC_OPERATOR:SEC_OPERATOR /home/SEC_OPERATOR/__info.txt
sudo chown SEC_OPERATOR:SEC_OPERATOR /home/SEC_OPERATOR/ban_user.txt
sudo chmod 0700 /home/SEC_OPERATOR/ban_user.txt
sudo chmod 0700 /home/SEC_OPERATOR/__info.txt
